### ISSUE TITLE
Fail to run check-cases.js and check-errors.js

### ISSUE THREAD

**Issue by halton** [domenic/webidl-class-generator#22]
```
$ node test/check-cases.js 
/home/halton/work/projects/github/webidl-class-generator/test/check-cases.js:6
import generate from "..";
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

$ node test/check-errors.js 
/home/halton/work/projects/github/webidl-class-generator/test/check-errors.js:6
import generate from "..";
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**Comment by halton** [comment]
Please ignore this issue, I'm aware of this test need run under mocha, will close it.
